owner: Linerly
repo: status

sites:
  - name: Website
    url: https://linerly.xyz/en
    icon: https://linerly.xyz/media/core/icon-optimized.svg

  - name: Immich
    url: https://media.linerly.xyz
    icon: https://media.linerly.xyz/favicon.png
    __dangerous__body_down: "Argo Tunnel error"

  - name: Statistics
    url: https://stats.linerly.xyz
    icon: https://static.zgo.at/favicon/apple-touch-icon.png

status-website:
  cname: status.linerly.xyz
  name: "Service Status - Linerly"
  logoUrl: https://linerly.xyz/assets/icon-optimized.svg
  favicon: https://linerly.xyz/favicon.ico
  faviconSvg: https://linerly.xyz/assets/icon-optimized.svg
  themeUrl: https://status.linerly.xyz/theme.css
  metaTags:
    - name: "theme-color"
      content: "#1e90ff"
    - name: "author"
      content: "Linerly"
    - name: "description"
      content: "See the status of Linerly's services"
    - name: "keywords"
      content: "Linerly, Status, Uptime, Downtime, Up, Down, Online, Offline, Upptime, GitHub, Pages, GitHub Pages"
