# Change these first
owner: Linerly # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://linerly.tk
    icon: https://linerly.tk/assets/favicon.ico
  - name: SearXNG
    url: https://searxng.linerly.tk
    icon: https://searxng.linerly.tk/static/themes/oscar/img/favicon.png
  - name: MortyProxy
    url: https://proxy.linerly.tk
  - name: LinerlyBot (Discord)
    url: https://linerlybot-discord.linerly.tk
    icon: https://linerly.tk/assets/linerlybot/linerlybot.png
  - name: Apkes
    url: https://apkes.linerly.tk
    icon: https://apkes.linerly.tk/icon.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  name: "Linerly's Service Status"
  introTitle: "This is where you can see all of my service's status."
  introMessage: "*All powered by Upptime (and GitHub)!*"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://linerly.tk
    - title: Blog
      href: https://linerly.tk/blog
  logoUrl: https://linerly.tk/assets/new-logo.png
  favicon: https://linerly.tk/assets/new-logo.png
  faviconSvg: https://linerly.tk/assets/new-logo.svg
  theme: ocean
  metaTags:
    - name: "theme-color"
      content: "#1e90ff"
    - name: "author"
      content: "Linerly"
    - name: "description"
      content: "Here you can see Linerly's service status."
    - name: "keywords"
      content: "Linerly, Status, Uptime, Downtime, Up, Down, Online, Offline, Upptime, GitHub, Pages, GitHub Pages, CI"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
