owner: Linerly
repo: status

sites:
  - name: Website
    url: https://linerly.tk
    icon: https://linerly.tk/assets/icon-optimized.svg
  - name: SearXNG
    url: https://searxng.linerly.tk
    icon: https://raw.githubusercontent.com/searxng/searxng/master/searx/static/themes/simple/img/favicon.svg
  - name: MortyProxy
    url: https://proxy.linerly.tk
  - name: LinerlyBot (Discord)
    url: https://linerlybot-discord.linerly.tk
    icon: https://linerly.tk/assets/linerlybot/linerlybot.png
  - name: Apkes
    url: https://apkes.linerly.tk
    icon: https://codeberg.org/Linerly/apkes/raw/branch/main/public/icons/icon.svg

status-website:
  cname: status.linerly.tk
  name: "Linerly's Service Status"
  introTitle: "See all the status of Linerly's services"
  introMessage: "Powered by Upptime on GitHub"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://linerly.tk
    - title: Blog
      href: https://linerly.tk/en/blog
  logoUrl: https://linerly.tk/assets/icon-optimized.svg
  faviconSvg: https://linerly.tk/assets/icon-optimized.svg
  theme: ocean
  metaTags:
    - name: "theme-color"
      content: "#1e90ff"
    - name: "author"
      content: "Linerly"
    - name: "description"
      content: "See the status of Linerly's services"
    - name: "keywords"
      content: "Linerly, Status, Uptime, Downtime, Up, Down, Online, Offline, Upptime, GitHub, Pages, GitHub Pages"
