owner: Linerly
repo: status

sites:
  - name: Website
    url: https://linerly.xyz/en
    icon: https://linerly.xyz/media/core/icon-optimized.svg

  - name: Apkes
    url: https://apkes.linerly.xyz
    icon: https://apkes.linerly.xyz/icons/icon.svg

  - name: Geora
    url: https://geora.linerly.xyz
    icon: https://geora.linerly.xyz/icons/icon.svg

  - name: Pegiatan
    url: https://pegiatan.linerly.xyz
    icon: https://pegiatan.linerly.xyz/icons/icon.svg

  - name: EcoTrek
    url: https://ecotrek.linerly.xyz
    icon: https://ecotrek.linerly.xyz/icons/icons.svg

  - name: EcoCalc
    url: https://ecocalc.linerly.xyz
    icon: https://ecocalc.linerly.xyz/icons/icon.svg

  - name: Nontrinsic
    url: https://nontrinsic.linerly.xyz
    icon: https://nontrinsic.linerly.xyz/favicon.png

  - name: Immich
    url: https://media.linerly.xyz
    icon: https://media.linerly.xyz/apple-icon-180.png

  - name: OwnTracks Frontend
    url: https://track.linerly.xyz/favicon.ico
    icon: "data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAJgCAACYAgAAAAAAAAAAAAC1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VxPv+0cT7/tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7RxPf+9gVP/v4VZ/7RxPf+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VxPv+4eEf/5c27/+vYyv+6fE3/tXE+/7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//1rGV//78+////v7/27ui/7VzQP+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+0cDz/yZhz//nz7//+/f3//v38//v39P/Mnnr/tHA9/7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+0cT3/v4Za/+3d0f/iyLT/zJ16/8ydev/iyLT/7+DV/8CHW/+0cT3/tXI//7VyP/+1cj//tXI//7VyP/+1cj//tnNB/9/Drf/kzLr/zqKA/7l6Sv+5eUn/zJ98/+TLuP/fw63/tnNB/7VyP/+1cj//tXI//7VyP/+1cj//tXE+/72BVP/q18n/2rie//Tq4v/UrY//1KyO//Pp4f/Zt53/6tfJ/72BVP+1cT7/tXI//7VyP/+1cj//tXI//7RxPf/AiF3/6tfI/7+EWP/KmnX/0qqL/9Kqi//Kmnb/v4VZ/+rXyf/AiFz/tHE9/7VyP/+1cj//tXI//7VyP/+1cT7/unxN/+rXyf/FkGn/tHA8/9i0mf/YtJn/tHA8/8WRaf/q18n/unxN/7VxPv+1cj//tXI//7VyP/+1cj//tXI//7RxPv/Vr5L/59LC/76EWP/dvab/3b2m/76EWP/n0sL/1a+S/7RxPv+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj7/uHdG/9q5n//s2s3/5My6/+TMuv/s2sz/2rmf/7h3Rv+1cj7/tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VxPv+2c0H/w41k/9GniP/Rp4j/w41k/7ZzQf+1cT7/tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7RwPf+0cDz/tHA8/7RwPf+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//tXI//7VyP/+1cj//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="

  - name: Home Assistant
    url: https://home.linerly.xyz
    icon: https://home.linerly.xyz/static/icons/favicon.ico

  - name: Linerlycraft Creative (Java)
    check: "tcp-ping"
    url: c.mc.linerly.xyz
    port: 25565
    icon: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAANm0lEQVR4XuWWeVCU+ZnHO5utbCq7NdlNJbuzlczEidEZZ52diTKjznggqMgplyCH3PfVgM19NfTFfQqKCirKDS2XyH2KaINyI9CNTlUqlWQrm81uzR7Bcb77vO1AkJ+ttgOmUv3Hp8puu9/f8/3wfp+3eSkLn0OHUfBSFh5Ch1HwRAsPoMNwAhahw3ACVNBhFDzxghI6DCdgAToMCVDOQ4dR8CTKOegwnID7+LOwMAvx/AxE96cgmptW/5v5zMaj4EmVs1iN5DUgmptC4pgCEX2dCBioQGB3DSIHepA0MUoippnPbyCcgBm8LiTzUxBSyIjeDrhVnIXJuCv0H22G/v9tg/mwP7wqLyJqsBvJU3fVn137/Q2AEzCNjUayMIWU6XuIGeqFb3UZzHuCof/Fdujj7ac4+O96sLoeiQB5FeLuDEA0O6b+7trrrSMKnkw5hY1CujAJ8f0xxI8MIrixFrYNCTD4zWdM8LUYfn4YJ2qkCG1tQOLdW3SNcRr262uuL5yASWwEkrkxCMduIby9Cc6VGTi8YA79r9iwGnm0CUbj9nArL0BETyuSJ25DOj/OnPMN4QRMYD2Rzo8hZfIOovrb4Mn1XOEC/T9uZgO+LP9N+6HPDz5VpYi52QXRtILuLE4Ee/YroOClKsexHsgWxiCeUSBuuBv+tWWw7OBD/z8/ZAO9Igf/bTdsmmIQ3FCJBEUfxLOj6jPVZ786nADuIt+AhXuQ3h9B0mg/QltqYF+fCINfHWACrAtUoUMqYzhVyXCqTQ7hvUFI50bZmV4eTsA9vCrSuREkjw9C0NUAl4pMHJm1hP7jZwy+3iz9DMajjvCoOI2ovhaq3BBk85wIdsYXoOClKe9CW1IXRiCiQ6PpcO/yIpjecof+/25hB91o/ms7jnUFwq+qBLE32yCeHqbZRtl5NUMCVPQFbVCO0EFDEHTUwbZNgIO/38EO9pox+PVncGwS0t3QBMnsMDuzZjgBI9CGVKUCKRP9CKi+gA96P4Ter3+EA9o83tabr34KpyVDhD7wAb+pnP44N5mZn4OCl65SQFtEk33wryzGtvb38dYAD1vu/g12/+FNdrgNxnppF8IeOSIOXhB87gd+4xVIZjgB7Mwa4ATcgVYob0M0QT9pqfvvtb+nFrDMB3NvYP8ff8IMut4YP9qOwCUbdfBlBA99EXLtEgkYYGfWDCfgNrRCOUwCeuB7tRDvtr/7lACOTUPfxs5f/hAHHr/FDP5NMXy8GR5LJoh57PFU+CcCfBAivwjJdD87s2YUvAzVMLRCSb/NJ7pJwGm6A7YyApb5ueI72P27daoF7RiHpQOIfOzKBH9aQCmk033szJrhBNyCViiHSEAXCSh4roBl3p/8O+z94sdsqJfk2CM9hC6dYAKv5YmAEhLQy86sGU7AELRCeZMEdD5TwNv9rAD1+wPfwoeqf8D+pZevhdGX2+C3ZIXYrzyZsKc/d0DZqLUGAT3szJpR8DJVN6EVykFIJjrgdzWfEeCX/4/wPvMjbOn9FiOB452hv4ber57/2DR4/DO4LRkh+rE7Ezz1D65oqTiMYa8dkN8wXXk/ackD2e1O4MsvQDbdzc6sGU7AILRCOUAC2klAHra1PS0gOOtN5BzdDInnJhxp/NuV9+3K/x5be/9q5fXW0e9iz+//mQlvt7QXgi9PMsGXqe00U4dfEfCVF87ft0Of8FPUBpmQgPMkoIudWTOcgAFohbKfBLSRgFwk+O5Qh1srgMOt5Icr7wv5b0PqsQnHK/70WY7tM29g3//8GOaPfoGQJTsm8FpWC2grMUD72YMrr2uDjEnAua8FPGPuZ6PgZan6oRXKPkgnbsCfBMgsd6rDJkS8hUNN33tKwOrAnIDl90PS33xawuAbz+z5auIfe+LiuA0GonetBF5LHQkIlRcjdbqTnVkznIA+aIWylwS0koAcEqC3EizbdDNkJ99Zeb1MfORbkLpvWnktDHkb7/f8qQ4fDHyfCbwayRdu6MrZzwReC3cHPBHQwc6sGRKw2AutUJGASRJQng2h7T5kmmxjQr+IVOd34HT5B+qnxosE5PzWmQm7mlteOzHgvQdlIVYIvXYWqTPt7MyaUfCyF3ugFaoeyCavI6A8C5EO5ki23IdUs18gy/hdJuiL4Kphee2fmNCrKZk+zoRe5qb3J+j01UeTvxkKw5wRdu0M0mba2Jk1wwnohlaouklAi1pAoKsLIu2tkWBzGKJje5Bu+q/INt7CBH0eWd7bV8ImfumJjN89eQqk/YfLyiNvNX1uH6HfQw89Pvtw3d8YtYG29Nd3RarAnwQUkYAb7Mya4QR0QStUXSSgmQRkwt0rFIEnfRHm6IhoOwskWhtAYvEJMkz+hcL9nAn7LJYFnFGdQI9sL+ro8VbdY46hQD0mPHe7iw9tQYnjPsgDrXA12Bnn+X7IDz+FuKgoElBIAlrZmTWj4OUsdkIrVJ1InWwiARmwD0iBq1c8fNz4CHL2xCkHe8QeN4XQ6gBk5jtpP7zHBF5LtsN7aL1kyIR9Gq7nu9HhZ4iGAAtUBjmglO+N02GhyBDEISVSCn6MBOEkIH3mOjuzZjgBHdAKVQcJaCQB6bDgF8I2MA9OvmK4e0bDzzUIIU5uiLC3RZztUaRY7qX98BHth61M8BUBBBv4CTKDn0Lu8BG6qOfN/qaQWOvjUog7zoQFI/tUNMQRIsRF5yA89hw840+TgNMkoIWdWTMKXu5iO7QhR9VOAhoQSAIORVTBOKwCx0KKYReQBWefZHh6RMDfxR+hjicRZWel3g9i9X74gMKy+0GTgCEvPTS67kGznxGKXY7ivK89fEyPIjc8ArIIIRKiMiGIPYPA+DK4J8phn3QF4Q0kYLaZgrW/LJyANmiFqg3pUw3g12Rjb3wn9kV34pBADpPQMlgFF8HePx0u3onwdg+n/eCDcAfaD8fNkWR9kPbDx1SL97F6P6wVwPW83+dTtPkdhjzAEuXB9Bv/mAk8LCwhCYuDMCoNUTGnERx3EV6JtXAStsJK1A8LSQsiW4qQSQKYmTXDCbgBbcm834SYjnMwSmvDjqQx7I4bxIGoGzhyqhZm/IuwCSqAg58Mbl5x6v0Q7OwBwQk7xNqaINlqP+2HHVSLJ/thtYBBrue+BmgMMEdV0AnquRc93vjIPBWr7nlMdB5C4y7AJ6ESJ4XNsE3pgYn4DgxkUziefw2J/ZeQNd/CzPscFLy8xVZoS46yBbKxGgga82GXVYhdwiHoJY7i09g+HIxsgVF4FSxCLtB+yFXvBw/PKNoPgeA7udJ+sEG8jRFSjn2GNLMPkXV0q/p53u17gHpugpqg47hMPT8bGkQ9j4KEeh4fnU09L4Z/wlW4JTXALrkT5uJbOCSdxCFJP5wLchB9g34DTNbTbNcpWOvLwgm4jlchZ6EZ6ZN1SOwrQUCZFGbSMuxMGsXHCXewN6YbBhGNtB/KYRlM+8E/Eyd9hLQfBAhw8aP94Ez7wZIem4cgstiFVn8j1Ada40qwC86F+iMvXKDueWJUBiJiiqjnl+GRWA+H5DYcEw3iiHQMB6UjsMk4j5DKNAgHLyFjWk7hm5k5XwAnoAWvSq6qGdlzDZDdrURMexE8iyUwTGlQ12JX/C3sj+5Q7wfT0MuwCirECb80uHon0H4IQ9BJb9oPDoi2NUMF9byE74OC8DCkCxKQHJlKPS9ASFwpvBNrqOfXYS3qg7FklIJPwFxWDd9SMeK7zyF1vBrZ843qWdbO9xIoePmLzfgm5BG5yiZkzdZDcucKIhpz4JSXjr3CLrWIPer90Er7oQbm/FLYBObD0VdK+yEWvm4hCKbHZlFYCPU8BqJICWKjc6nn5+FLPXdJaqKed8OU67l0CkaSG3AvkiK6tQDS0XJk35dT8Cb1DM+a6yUgAQ+asC4sNpGIBmRO1yB5qBT86lS6Rc/gE+Ew7YcRfBbbS/uhGUfDK2k/nMfxABLlI4K7uwDSiBTqeRZOxZ5FQDzX82uwT+6AhbrnEzCU3IRDbg5OyTMhvn2ZZNdR8Ab1mcwc2sEJaMR6krfYQPtBjvSJSiT0noX/pRSYSMrpbriLTxJu037ogmFEA0zCrtJ+OAs73zTqeSGCqOeeiXXU8xuwpJ4bSe7R7X4X1umlCK4QQzhwHhlT1ST5Gp3BnvuKKHgFDxqwEeQvXkPOXB1S715BTFs+PM6IYJDS/PVjc4j2QzsOC+phGlJCPa+Gs7AFNilcz0co+CTMZPXwLaE7o4t+34+XI3e+Xn3Nteeoz3pF6LucAO6iG0e+qh7Zs9W0H0ohaMiAY04GPhX2YmfiPeyJHYC+oBHHqedm4tswpOBHJB1wK6SeX8+GbPQySayha8iZ664TnADu4hvMohx5yjraDxVIHiwGv1IEq7RifCy8g4/jh3FYOk7hh3EiOx/hdTKIhy8ga6YSeao69lrri4J3+kE9XhcFi3XIW6hBxngZErsLEHg5BdY5NXAoqEBIRQqE/fRTdvKq+jMFi+z3NwBOQB1eNwWqWuTOVSF97BLEt4rpL35OLSVvvoqC1zKf30A4AdyBfx4KVNRvZbWagsUa5v9fAwpe4YMa6DCcgGroMJyAKugwCl7Rg0roMJyACugwJOBhOXQYBe/Mw6vQYTgBV6DDcALKoMMoeGcfXlb8ZVC2EVz8f96glhh4vWzuAAAAAElFTkSuQmCC"
    
  - name: Statistics
    url: https://stats.linerly.xyz
    icon: https://static.zgo.at/favicon/apple-touch-icon.png

status-website:
  cname: status.linerly.xyz
  name: "Service Status - Linerly"
  logoUrl: https://linerly.xyz/assets/icon-optimized.svg
  favicon: https://linerly.xyz/favicon.ico
  faviconSvg: https://linerly.xyz/assets/icon-optimized.svg
  themeUrl: https://status.linerly.xyz/theme.css
  metaTags:
    - name: "theme-color"
      content: "#1e90ff"
    - name: "author"
      content: "Linerly"
    - name: "description"
      content: "See the status of Linerly's services"
    - name: "keywords"
      content: "Linerly, Status, Uptime, Downtime, Up, Down, Online, Offline, Upptime, GitHub, Pages, GitHub Pages"
