owner: Linerly
repo: status

sites:
  - name: Website
    url: https://linerly.xyz
    icon: https://linerly.xyz/assets/icon-optimized.svg

  - name: Nextcloud
    url: https://cloud.linerly.xyz
    icon: https://cloud.linerly.xyz/core/img/favicon.ico

  - name: GoatCounter
    url: https://stats.linerly.xyz
    icon: https://static.zgo.at/favicon/apple-touch-icon.png

status-website:
  baseUrl: /
  cname: status.linerly.xyz
  name: "Linerly's Service Status"
  introTitle: "See all the status of Linerly's services"
  introMessage: "Powered by Upptime on GitHub"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://linerly.xyz
    - title: Blog
      href: https://linerly.xyz/en/blog
  logoUrl: https://linerly.xy/assets/icon-optimized.svg
  faviconSvg: https://linerly.xyz/assets/icon-optimized.svg
  theme: ocean
  metaTags:
    - name: "theme-color"
      content: "#1e90ff"
    - name: "author"
      content: "Linerly"
    - name: "description"
      content: "See the status of Linerly's services"
    - name: "keywords"
      content: "Linerly, Status, Uptime, Downtime, Up, Down, Online, Offline, Upptime, GitHub, Pages, GitHub Pages"
