owner: Linerly
repo: status

sites:
  - name: Website
    url: https://linerly.codeberg.page
    icon: https://linerly.codeberg.page/assets/icon-optimized.svg

  - name: LinerlyBot (Discord)
    url: https://linerlybot-discord.linerly.repl.co
    icon: https://linerly.codeberg.page/assets/linerlybot/linerlybot.png

status-website:
  baseUrl: /status
  name: "Linerly's Service Status"
  introTitle: "See all the status of Linerly's services"
  introMessage: "Powered by Upptime on GitHub"
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://linerly.codeberg.page
    - title: Blog
      href: https://linerly.codeberg.page/en/blog
  logoUrl: https://linerly.codeberg.page/assets/icon-optimized.svg
  faviconSvg: https://linerly.codeberg.page/assets/icon-optimized.svg
  theme: ocean
  metaTags:
    - name: "theme-color"
      content: "#1e90ff"
    - name: "author"
      content: "Linerly"
    - name: "description"
      content: "See the status of Linerly's services"
    - name: "keywords"
      content: "Linerly, Status, Uptime, Downtime, Up, Down, Online, Offline, Upptime, GitHub, Pages, GitHub Pages"
